version: '3.1'

services:

  drupal:
    image: registry.cn-hangzhou.aliyuncs.com/catshop/catshop:latest
    ports:
      - 8080:80
    volumes:
      - .:/app/web/profiles/custom/catshop
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ./data/drupal:/app/web/sites
      # 使用本地版本，直到 https://www.drupal.org/project/erd/issues/2933522 被合并
      - /d/DrupalProjects/erd:/app/web/modules/contrib/erd
    restart: always

  db:
    image: mysql
    ports:
      - "3388:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123